substitutions:
  name: "blue-wheel"
  friendly_name: "Blue Wheel"
  device_description: "Waveshare ESP32S3-1.8-inch "
  project_name: "myprojects.Project-Blue-Wheel"
  project_version: "1.0.0"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  project:
    name: "${project_name}"
    version: "${project_version}"
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 80000000L
    board_build.f_cpu: 240000000L

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

psram:
  mode: octal

logger:

api:
  encryption:
    key: "JVMKWt6yFfphJLHR22IYd5LOPI32I1oHHCaVJ/FkXHI="
  id: my_api
  on_client_connected: 
    then:
      - lambda: |-
                {
                  lv_led_set_color(id(ha_led), lv_color_hex(0x00ff00));
                  lv_obj_add_flag(id(busy_spinner), LV_OBJ_FLAG_HIDDEN);
                }
  on_client_disconnected: 
    then:
      - lambda: |-
                {
                  lv_led_set_color(id(ha_led), lv_color_hex(0x00ff00));
                }
          

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.104
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 8.8.8.8

  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "fallbackPassw0rd"

spi:
  id: display_qspi
  type: quad
  clk_pin: 13
  data_pins: [15, 16, 17, 18]

i2c:
  sda: 11
  scl: 12
  id: touchscreen_bus

# Deep sleep configuration - wakes up on encoder rotation
deep_sleep:
  id: deep_sleep_control
  esp32_ext1_wakeup:
    mode: ANY_LOW
    pins:
      - number: GPIO7
        allow_other_uses: true
      - number: GPIO8
        allow_other_uses: true

globals:
  - id: current_page
    type: int
    restore_value: no
    initial_value: '1'
  - id: pending_cover_position
    type: int
    restore_value: no
    initial_value: '0'
  - id: cover_update_pending
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: pending_led_brightness
    type: int
    restore_value: no
    initial_value: '0'
  - id: led_update_pending
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: encoder_value
    type: int
    initial_value: '0'
    restore_value: true

touchscreen:
  platform: cst816
  id: my_touchscreen
  interrupt_pin: GPIO9
  reset_pin: GPIO10
  on_release:
    - if:
        condition: lvgl.is_paused
        then:
          - logger.log: "LVGL resuming from touch"
          - lvgl.resume:
          - lvgl.widget.redraw:
          - light.turn_on: display_backlight

light:
  - platform: monochromatic
    id: display_backlight
    name: "Backlight"
    output: backlight_pwm
    default_transition_length:
      milliseconds: 30
    initial_state:
      brightness: 50%
    restore_mode: ALWAYS_ON

  - platform: lvgl
    name: "Living One"
    id: living_1_light
    widget: led_indicator_1
    default_transition_length: 500ms

switch:
  - platform: lvgl
    id: light_1_switch
    name: "Living 1 switch"
    widget: living_1_switch_widget

font:
  - file: "gfonts://Roboto"
    id: roboto_20
    size: 20
    glyphsets:
      - GF_Latin_Core
  - file: "gfonts://Roboto"
    id: roboto_32
    size: 32
    glyphsets:
      - GF_Latin_Core
  - file: "gfonts://Roboto"
    id: roboto_88
    size: 88
    glyphsets:
      - GF_Latin_Core   
         
output:
  - platform: ledc
    pin:
      number: GPIO47
    id: backlight_pwm

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Asia/Kolkata

display:
  - platform: qspi_dbi
    id: my_display
    model: CUSTOM
    data_rate: 80MHz
    color_order: rgb
    dimensions:
      height: 360
      width: 360
    cs_pin: 14
    reset_pin: 21
    invert_colors: true
    rotation: 180
    auto_clear_enabled: false
    init_sequence:
      - [0xF0, 0x28]
      - [0xF2, 0x28]
      - [0x73, 0xF0]
      - [0x7C, 0xD1]
      - [0x83, 0xE0]
      - [0x84, 0x61]
      - [0xF2, 0x82]
      - [0xF0, 0x00]
      - [0xF0, 0x01]
      - [0xF1, 0x01]
      - [0xB0, 0x56]
      - [0xB1, 0x4D]
      - [0xB2, 0x24]
      - [0xB4, 0x87]
      - [0xB5, 0x44]
      - [0xB6, 0x8B]
      - [0xB7, 0x40]
      - [0xB8, 0x86]
      - [0xBA, 0x00]
      - [0xBB, 0x08]
      - [0xBC, 0x08]
      - [0xBD, 0x00]
      - [0xC0, 0x80]
      - [0xC1, 0x10]
      - [0xC2, 0x37]
      - [0xC3, 0x80]
      - [0xC4, 0x10]
      - [0xC5, 0x37]
      - [0xC6, 0xA9]
      - [0xC7, 0x41]
      - [0xC8, 0x01]
      - [0xC9, 0xA9]
      - [0xCA, 0x41]
      - [0xCB, 0x01]
      - [0xD0, 0x91]
      - [0xD1, 0x68]
      - [0xD2, 0x68]
      - [0xF5, 0x00, 0xA5]
      - [0xDD, 0x4F]
      - [0xDE, 0x4F]
      - [0xF1, 0x10]
      - [0xF0, 0x00]
      - [0xF0, 0x02]
      - [
          0xE0,
          0xF0,
          0x0A,
          0x10,
          0x09,
          0x09,
          0x36,
          0x35,
          0x33,
          0x4A,
          0x29,
          0x15,
          0x15,
          0x2E,
          0x34,
        ]
      - [
          0xE1,
          0xF0,
          0x0A,
          0x0F,
          0x08,
          0x08,
          0x05,
          0x34,
          0x33,
          0x4A,
          0x39,
          0x15,
          0x15,
          0x2D,
          0x33,
        ]
      - [0xF0, 0x10]
      - [0xF3, 0x10]
      - [0xE0, 0x07]
      - [0xE1, 0x00]
      - [0xE2, 0x00]
      - [0xE3, 0x00]
      - [0xE4, 0xE0]
      - [0xE5, 0x06]
      - [0xE6, 0x21]
      - [0xE7, 0x01]
      - [0xE8, 0x05]
      - [0xE9, 0x02]
      - [0xEA, 0xDA]
      - [0xEB, 0x00]
      - [0xEC, 0x00]
      - [0xED, 0x0F]
      - [0xEE, 0x00]
      - [0xEF, 0x00]
      - [0xF8, 0x00]
      - [0xF9, 0x00]
      - [0xFA, 0x00]
      - [0xFB, 0x00]
      - [0xFC, 0x00]
      - [0xFD, 0x00]
      - [0xFE, 0x00]
      - [0xFF, 0x00]
      - [0x60, 0x40]
      - [0x61, 0x04]
      - [0x62, 0x00]
      - [0x63, 0x42]
      - [0x64, 0xD9]
      - [0x65, 0x00]
      - [0x66, 0x00]
      - [0x67, 0x00]
      - [0x68, 0x00]
      - [0x69, 0x00]
      - [0x6A, 0x00]
      - [0x6B, 0x00]
      - [0x70, 0x40]
      - [0x71, 0x03]
      - [0x72, 0x00]
      - [0x73, 0x42]
      - [0x74, 0xD8]
      - [0x75, 0x00]
      - [0x76, 0x00]
      - [0x77, 0x00]
      - [0x78, 0x00]
      - [0x79, 0x00]
      - [0x7A, 0x00]
      - [0x7B, 0x00]
      - [0x80, 0x48]
      - [0x81, 0x00]
      - [0x82, 0x06]
      - [0x83, 0x02]
      - [0x84, 0xD6]
      - [0x85, 0x04]
      - [0x86, 0x00]
      - [0x87, 0x00]
      - [0x88, 0x48]
      - [0x89, 0x00]
      - [0x8A, 0x08]
      - [0x8B, 0x02]
      - [0x8C, 0xD8]
      - [0x8D, 0x04]
      - [0x8E, 0x00]
      - [0x8F, 0x00]
      - [0x90, 0x48]
      - [0x91, 0x00]
      - [0x92, 0x0A]
      - [0x93, 0x02]
      - [0x94, 0xDA]
      - [0x95, 0x04]
      - [0x96, 0x00]
      - [0x97, 0x00]
      - [0x98, 0x48]
      - [0x99, 0x00]
      - [0x9A, 0x0C]
      - [0x9B, 0x02]
      - [0x9C, 0xDC]
      - [0x9D, 0x04]
      - [0x9E, 0x00]
      - [0x9F, 0x00]
      - [0xA0, 0x48]
      - [0xA1, 0x00]
      - [0xA2, 0x05]
      - [0xA3, 0x02]
      - [0xA4, 0xD5]
      - [0xA5, 0x04]
      - [0xA6, 0x00]
      - [0xA7, 0x00]
      - [0xA8, 0x48]
      - [0xA9, 0x00]
      - [0xAA, 0x07]
      - [0xAB, 0x02]
      - [0xAC, 0xD7]
      - [0xAD, 0x04]
      - [0xAE, 0x00]
      - [0xAF, 0x00]
      - [0xB0, 0x48]
      - [0xB1, 0x00]
      - [0xB2, 0x09]
      - [0xB3, 0x02]
      - [0xB4, 0xD9]
      - [0xB5, 0x04]
      - [0xB6, 0x00]
      - [0xB7, 0x00]
      - [0xB8, 0x48]
      - [0xB9, 0x00]
      - [0xBA, 0x0B]
      - [0xBB, 0x02]
      - [0xBC, 0xDB]
      - [0xBD, 0x04]
      - [0xBE, 0x00]
      - [0xBF, 0x00]
      - [0xC0, 0x10]
      - [0xC1, 0x47]
      - [0xC2, 0x56]
      - [0xC3, 0x65]
      - [0xC4, 0x74]
      - [0xC5, 0x88]
      - [0xC6, 0x99]
      - [0xC7, 0x01]
      - [0xC8, 0xBB]
      - [0xC9, 0xAA]
      - [0xD0, 0x10]
      - [0xD1, 0x47]
      - [0xD2, 0x56]
      - [0xD3, 0x65]
      - [0xD4, 0x74]
      - [0xD5, 0x88]
      - [0xD6, 0x99]
      - [0xD7, 0x01]
      - [0xD8, 0xBB]
      - [0xD9, 0xAA]
      - [0xF3, 0x01]
      - [0xF0, 0x00]
      - [0xF0, 0x01]
      - [0xF1, 0x01]
      - [0xA0, 0x0B]
      - [0xA3, 0x2A]
      - [0xA5, 0xC3]
      - delay 1ms
      - [0xA3, 0x2B]
      - [0xA5, 0xC3]
      - delay 1ms
      - [0xA3, 0x2C]
      - [0xA5, 0xC3]
      - delay 1ms
      - [0xA3, 0x2D]
      - [0xA5, 0xC3]
      - delay 1ms
      - [0xA3, 0x2E]
      - [0xA5, 0xC3]
      - delay 1ms
      - [0xA3, 0x2F]
      - [0xA5, 0xC3]
      - delay 1ms
      - [0xA3, 0x30]
      - [0xA5, 0xC3]
      - delay 1ms
      - [0xA3, 0x31]
      - [0xA5, 0xC3]
      - delay 1ms
      - [0xA3, 0x32]
      - [0xA5, 0xC3]
      - delay 1ms
      - [0xA3, 0x33]
      - [0xA5, 0xC3]
      - delay 1ms
      - [0xA0, 0x09]
      - [0xF1, 0x10]
      - [0xF0, 0x00]
      - [0x2A, 0x00, 0x00, 0x01, 0x67]
      - [0x2B, 0x01, 0x68, 0x01, 0x68]
      - [0x4D, 0x00]
      - [0x4E, 0x00]
      - [0x4F, 0x00]
      - [0x4C, 0x01]
      - delay 10ms
      - [0x4C, 0x00]
      - [0x2A, 0x00, 0x00, 0x01, 0x67]
      - [0x2B, 0x00, 0x00, 0x01, 0x67]
      - [0x3A, 0x55]
      - [0x21, 0x00]
      - [0x11, 0x00]
      - delay 120ms
      - [0x29, 0x00]

binary_sensor:
  - platform: gpio
    id: encoder_pin_a
    pin:
      number: GPIO7
      mode: INPUT_PULLUP
      allow_other_uses: true
    on_press:
       then:
            - light.turn_on:
                id: living_1_light
                brightness: !lambda 'return id(living_1_light).current_values.is_on();'
             
            - if:
                condition: lvgl.is_paused
                then:
                  - logger.log: "LVGL resuming from encoder"
                  - lvgl.resume:
                  - lvgl.widget.redraw:
                  - light.turn_on: display_backlight

  - platform: gpio
    id: encoder_pin_b
    pin:
      number: GPIO8
      mode: INPUT_PULLUP
      allow_other_uses: true
    on_press:
      then:
            - light.turn_on:
                id: living_1_light
                brightness: !lambda 'return id(living_1_light).current_values.is_on();'

            - if:
                condition: lvgl.is_paused
                then:
                  - logger.log: "LVGL resuming from encoder"
                  - lvgl.resume:
                  - lvgl.widget.redraw:
                  - light.turn_on: display_backlight

image:
  - file: "images/background.png"  # Place in config dir
    id: bg_image
    resize: 360x360  # Match display resolution
    type: rgb565
    transparency: opaque
  
lvgl:
  on_idle:
    timeout: 30s
    then:
      - logger.log: "LVGL is idle - preparing for deep sleep"
      - light.turn_off: display_backlight
      - lvgl.pause:
      - delay: 1800s
      - logger.log: "Entering deep sleep"
      - deep_sleep.enter: deep_sleep_control
  
  displays: 
    - my_display

  disp_bg_image: bg_image
  disp_bg_opa: 100%

  top_layer:
    widgets:
      - label:
          id: battery_percentage_label
          align: bottom_mid
          y: -10
          text: " "
          text_font: roboto_20
          text_color: 0xFFFFFF
          clickable: false
      
      - led:
          id: ha_led
          align: bottom_mid
          y: -30
          clickable: false
      
      - spinner:
          id: busy_spinner
          align: CENTER
          y: 95
          height: 50
          width: 50
          spin_time: 1s
          arc_length: 60deg
          arc_width: 8
          indicator:
            arc_color: 0x18bcf2
            arc_width: 8
 
  pages:
    # First Page
    - id: page_1
      widgets:
        - obj:
            id: background_1
            x: 0
            y: 0
            width: 360
            height: 360
            bg_color: 0x000000
            border_width: 0
            pad_all: 0
        
        - switch:
            id: led_1_switch_widget
            width: 150
            height: 80
            align: center
            on_boot:
              - lambda: |-
                        {
                          ESP_LOGD("DEBUG", "Currrent state of living light : %d", id(living_1_light).current_values.is_on());
                        }
                
            on_value:
              then:
              - if:
                  condition:
                    - lambda: 'return x == 1;'
                  then:
                    - light.turn_on: living_1_light
                    - lambda: 'ESP_LOGI("INFO","Living one ON");'
                  else:
                    - light.turn_off: living_1_light
                    - lambda: 'ESP_LOGI("INFO","Living one OFF");'

        - led:
            id: led_indicator_1
            width: 50
            height: 50
            x: -130
            y: -156
            align: bottom_mid
            color: 0x00FF00
        
        - label:
            id: led_1_brightness_label
            align_to:
              id: led_indicator_1
              align: bottom_mid
            x: 10
            y: -15
            text: "--%"
            text_font: roboto_32
            text_color: 0xFFFFFF

        - label:
            id: page1_label
            align: top_mid
            y: 40
            text: "Page 1"
            text_font: roboto_32
            text_color: 0xFFFFFF

      on_swipe_left:
        - lambda: 'id(current_page) = 2;'
        - lvgl.page.show:
            id: page_2
            animation: OUT_LEFT

      on_swipe_right:
        - lambda: 'id(current_page) = 2;'
        - lvgl.page.show:
            id: page_2 
            animation: OUT_RIGHT
                  
    - id: page_2
      widgets:
        - obj:
            id: background_2
            x: 0
            y: 0
            width: 360
            height: 360
            bg_color: 0x000000
            border_width: 0
            pad_all: 0

        - switch:
            id: led_2_switch_widget
            width: 150
            height: 30
            align: center

        - label:
            id: page2_label
            align: top_mid
            y: 40
            text: "Page 2"
            text_font: roboto_32
            text_color: 0xFFFFFF
    
      on_swipe_left:
        - lambda: 'id(current_page) = 1;'
        - lvgl.page.show:
            id: page_1
            animation: OUT_LEFT
      on_swipe_right:
        - lambda: 'id(current_page) = 1;'
        - lvgl.page.show:  
            id: page_1
            animation: OUT_RIGHT


  
sensor:
  - platform: adc
    pin: 1
    name: "Battery Voltage"
    id: battery_voltage
    attenuation: 12db
    accuracy_decimals: 2
    update_interval: 10s
    unit_of_measurement: "V"
    icon: mdi:battery-medium
    filters:
      - multiply: 2.0
      - median:
          window_size: 7
          send_every: 7
          send_first_at: 7
      - throttle: 1min
    on_value:
      then:
        - component.update: battery_percentage

  - platform: template
    id: battery_percentage
    name: "Battery Percentage"
    lambda: return id(battery_voltage).state;
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: mdi:battery-medium
    filters:
      - calibrate_linear:
         method: exact
         datapoints:
          - 2.80 -> 0.0
          - 3.10 -> 10.0
          - 3.30 -> 20.0
          - 3.45 -> 30.0
          - 3.60 -> 40.0
          - 3.70 -> 50.0
          - 3.75 -> 60.0
          - 3.80 -> 70.0
          - 3.90 -> 80.0
          - 4.00 -> 90.0
          - 4.20 -> 100.0
      - lambda: |-
          if (x > 100) return 100;
          if (x < 0) return 0;
          return x;
    on_value:
      then:
        - lvgl.label.update:
            id: battery_percentage_label
            text: !lambda |-
              static char buf[8];
              if ((int)x < 0 || (int)x > 100) {
                snprintf(buf, sizeof(buf), "%s", "---%");
                return buf;
              } else {
                snprintf(buf, sizeof(buf), "%d%%", (int)x);
                return buf;
              }
  
    
              